url: "https://furkanonder.github.io/"
title: Furkan Taha ÖNDER
desc: Furkan Taha ÖNDER'in kişisel blogu
author:
  name: Furkan Taha ÖNDER

disqus: ""
google_analytics: "UA-108363583-1"

timezone: "Europe/Istanbul"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title
paginate: 5

plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


